project_kkal/calorie_calculator/calorie_calculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ingredients/", include("ingredients.urls")),
]

project_kkal/calorie_calculator/ingredients/urls.py
from django.urls import path
from . import views
from .views import index, details, LogoutView, LoginView, register

app_name = "ingredients"

urlpatterns = [
    path('', index, name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('<int:pk>/', details, name='details'),
    path('outcome/', views.ingredient_outcome_view, name='outcome'),
    path('outcome/delete/<int:ingredient_id>', views.ingredient_delete, name='ingredient_delete'),
    ]

project_kkal/calorie_calculator/ingredients/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    def __str__(self):
        return f'{self.username}'


class Ingredient(models.Model):

    name = models.CharField(max_length=70)
    protein = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    fats = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    carbohydrate = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    calorie = models.DecimalField(max_digits=5, decimal_places=2, default=0, blank=True)
    quantity = models.IntegerField(default=1, null=True, blank=True)

    def __str__(self):
        return str(self.name)


class ItemConsumed(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ingredient_consumed = models.ForeignKey(Ingredient, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} - {self.ingredient_consumed}'

project_kkal/calorie_calculator/ingredients/forms.py
from django.contrib.auth.forms import AuthenticationForm as AuthenticationFormGeneric
from django.forms import Widget
from django import forms
from django.contrib.auth.forms import UserCreationForm
from ingredients.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class AuthenticationForm(AuthenticationFormGeneric):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            widget: Widget = field.widget
            widget.attrs["class"] = "form-control"

project_kkal/calorie_calculator/ingredients/views.py
from django.contrib.auth import login, authenticate
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from ingredients.forms import AuthenticationForm, RegisterForm
from ingredients.models import Ingredient, ItemConsumed
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    LoginView as LoginViewGeneric,
    LogoutView as LogoutViewGeneric,
)


def index(request: HttpRequest):
    context = {"ingredients": Ingredient.objects.order_by("pk").all()
               }
    return render(request=request, template_name='ingredients/index.html', context=context)


def register(request: HttpRequest):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/ingredients')
    else:
        form = RegisterForm()
    return render(request=request, template_name='ingredients/register.html', context={'form': form})


class LoginView(LoginViewGeneric):
    form_class = AuthenticationForm
    next_page = reverse_lazy('ingredients:index')


class LogoutView(LogoutViewGeneric):
    next_page = reverse_lazy('ingredients:index')


def details(request: HttpRequest, pk: int):
    context = {"ingredient": get_object_or_404(Ingredient, pk=pk),
               }
    return render(request=request, template_name='ingredients/details.html', context=context)


def ingredient_outcome_view(request: HttpRequest):
    if request.method == 'POST':
        ingredients = Ingredient.objects.all()
        ingredient = request.POST['ingredient_consumed']
        ingredient_consumed = Ingredient.objects.get(name=ingredient)
        user = request.user
        outcome = ItemConsumed(user=user, ingredient_consumed=ingredient_consumed)
        outcome.save()

    else:
        ingredients = Ingredient.objects.all()

    user_outcome = ItemConsumed.objects.filter(user=request.user)

    total_calories = 0
    for item in user_outcome:
        total_calories += item.ingredient_consumed.calorie

    context = {'ingredients': ingredients, 'user_outcome': user_outcome, 'total_calories': total_calories}
    return render(request=request, template_name='ingredients/outcome.html', context=context)


def ingredient_delete(request: HttpRequest, ingredient_id):

    ingredient_consumed = ItemConsumed.objects.filter(id=ingredient_id)

    if request.method == 'POST':
        ingredient_consumed.delete()
        return redirect('/ingredients/outcome')

    return render(request=request, template_name='ingredients/ingredient_delete.html')

project_kkal/calorie_calculator/ingredients/templates/ingredients/base.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>{% block title %}Ingredients{% endblock %}</title>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css' rel='stylesheet'>
    </head>

    <body>

        <nav class='navbar navbar-expand-lg navbar-dark bg-primary'>
            <div class='container-fluid'>
             <i class='fas fa-pepper-hot fa-2xl'></i> <h2>Ingredients </h2>

                <div class='collapse navbar-collapse' id='navbarColor'>
                    <ul class='navbar-nav me-auto'>
                        <li class='nav-item'>
                            <a class='nav-link' href="{% url 'ingredients:index' %}">
                                <i class='fas fa-list'></i> Ingredients List
                            </a>
                        </li>
                       {% if user.is_authenticated %}

                            <li class='nav-item'>
                                <a class='nav-link' href="{% url 'ingredients:outcome' %}">
                                    <i class='fas fa-utensils'></i> Ingredients outcome
                                </a>
                            </li>
                        {% endif %}
                    </ul>

                    <ul class='navbar-nav ms-auto'>
                        {% if user.is_authenticated %}
                        <li class='nav-item dropdown'>
                            <a class='nav-link dropdown-toggle' data-bs-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>
                                <i class='fas fa-user fa-fw fa-lg'></i>
                            </a>
                            <div class='dropdown-menu dropdown-menu-end'>

                                <div class='dropdown-divider'></div>
                                <a class='dropdown-item' href="{% url 'ingredients:logout' %}">
                                    <i class='fas fa-sign-out-alt'></i> Log Out
                                </a>
                            </div>
                        </li>
                        {% else %}
                        <li class='nav-item'>
                            <a class='nav-link' href="{% url 'ingredients:login' %}">
                                <i class='fas fa-sign-in-alt'></i> Log In
                            </a>
                        </li>
                        <li class='nav-item'>
                            <a class='nav-link' href="{% url 'ingredients:register' %}">
                                <i class='fas fa-user-plus'></i> Register
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <main>
            <div class='container'>
                {% block body %}
                {% endblock %}
            </div>
        </main>


        {% block script %}                                                                                                      
        <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'></script>                    
        {% endblock %}                                                                                                          
                                                                                                                         
    </body>
</html>

project_kkal/calorie_calculator/ingredients/templates/ingredients/details.html
{% extends 'ingredients/base.html' %}

{% block title %}
  {{ ingredient.name }} details
{% endblock %}

{% block body %}
<h2>{{ ingredient.name }}</h2>
<div class='my-3'>
  <p>Protein: {{ ingredient.protein }}</p>
  <p>Fats: {{ ingredient.fats }}</p>
  <p>Carbohydrate: {{ ingredient.carbohydrate }}</p>
</div>
    <p class='card-text'>
                            <div class='my-3'>
                                <strong>{{ ingredient.calorie}} calorie</strong> in {{ ingredient.quantity}} grams
                            </div>
                        </p>
<div class="my-2">
  <a href="{% url 'ingredients:index' %}">Back to ingredients list</a>
  </div>


{% endblock %}

project_kkal/calorie_calculator/ingredients/templates/ingredients/index.html
{% extends 'ingredients/base.html' %}

{% block title %}
  Ingredients list
{% endblock %}

{% block body %}
<table class="table table-bordered">
  <thead>
    <tr class="table-primary">
      <th scope="col">#</th>
      <th scope="col">INGREDIENT</th>
      <th scope="col">CALORIES</th>
      <th scope="col">QUANTITY / gram</th>
    </tr>
  </thead>
  <tbody>
    {% for ingredient in ingredients %}

        <tr class="table-secondary">

        <th scope="row"><a href="{% url 'ingredients:details' ingredient.pk %}">{{ ingredient.pk }}</a></th>
        <td>{{ ingredient.name }}</td>
        <td>{{ ingredient.calorie }}</td>
        <td>{{ ingredient.quantity }}</td>

        </tr>

      {% endfor %}
  </tbody>
</table>

{% endblock %}

project_kkal/calorie_calculator/ingredients/templates/ingredients/ingredient_delete.html
{% extends 'ingredients/base.html' %}

{% block title %}Ingredients | Delete {% endblock %}

{% block body %}
<div class='py-4 mt-auto'>
    <div class='container-fluid px-4'>
            <div class='row justify-content-center'>
                <div class='col-xl-12'>
                    <div class='card bg-light mb-3'>
                        <div class='card-body'>

                            <div class='form-group'>
                                <form method='POST'>
                                    {% csrf_token %}

                                    Are you sure you want to remove this ingredient?
                                    <button type='submit' class='btn btn-danger'>Delete</button>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock %}

project_kkal/calorie_calculator/ingredients/templates/ingredients/outcome.html
{% extends 'ingredients/base.html' %}

{% load static %}

{% block title %}Ingredients | Ingredients Consumed{% endblock %}

{% block body %}

<div class='py-4 mt-auto'>
    <div class='container-fluid px-4'>
        <div class='row justify-content-center'>
            <div class='col-xl-12'>
                    <div class='row'>
                        <div class='col-md-6 mt-4'>
                            <div class='card bg-light mb-3'>
                                <div class='card-header'>
                                    <h5>Select an ingredient to add it to the consumed ingredients</h5>
                                </div>
                                <div class='card-body'>
                                    <div class='form-group'>
                                        <form method='POST'>
                                            {% csrf_token %}
                                            <div class='form-group'>
                                                <div class='row'>
                                                    <div class='col-8'>
                                                        <select class='form-select' name='ingredient_consumed' id='ingredient_consumed'>
                                                            {% for ingredient in ingredients %}
                                                                <option value='{{ingredient.name}}'>
                                                                    {{ ingredient.name }}
                                                                </option>
                                                            {% endfor %}
                                                        </select>
                                                    </div>
                                                    <div class='col-4'>
                                                        <button type='submit' class='btn btn-primary'>
                                                            Add Ingredient
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                            <div class='card bg-light mb-3'>

                                <div class='card-header'>
                                    <h5>Ingredients Consumed Today</h5>
                                    <h5><strong class='text-primary'>{% now 'D, jS F Y' %}</strong></h5>
                                </div>
                                <div class='card-body'>

                                    <table  class='table table-hover'>
                                        <thead>
                                            <tr>
                                                <th scope='col' class='col-md-2'>Food Item</th>
                                                <th scope='col' class='col-md-2'>Calories</th>
                                                <th scope='col' class='col-md-2'>Fat (g) in 100g</th>
                                                <th scope='col' class='col-md-2'>Carbs (g) in 100g</th>
                                                <th scope='col' class='col-md-2'>Protein (g) in 100g</th>
                                                <th scope='col' class='col-md-2'></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for ingredient_item in user_outcome %}
                                            <tr>
                                                <td class='col-md-2'>{{ ingredient_item.ingredient_consumed.name }}</td>
                                                <td class='col-md-2'>{{ ingredient_item.ingredient_consumed.calorie }}</td>
                                                <td class='col-md-2'>{{ ingredient_item.ingredient_consumed.fats }}</td>
                                                <td class='col-md-2'>{{ ingredient_item.ingredient_consumed.carbohydrate }}</td>
                                                <td class='col-md-2'>{{ ingredient_item.ingredient_consumed.protein }}</td>
                                                  <td>
                                                    <a class='btn btn-danger' href="{% url 'ingredients:ingredient_delete' ingredient_item.id %}">
                                                        <i class='fas fa-trash-alt'></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}

                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                 </div>
             </div>
        </div>
</div>
 <div class='col-md-6 mt-4'>

                            <div class='card bg-light mb-3'>
                                <div class='card-header'>
                                    <h5>Daily Calorie Goal for man  - <strong class='text-primary'>2,000 calories</strong></h5>
                                     <h5>Daily Calorie Goal for women  - <strong class='text-primary'>1,800 calories</strong></h5>
                                </div>
                        </div>
                    </div>
    <div class='col-md-6 mt-4'>
    <div class='card bg-light mb-3'>
     <div class='card-header'>
     {% if user_outcome %}
        <h3>Total number of items consumed today: {{user_outcome|length}}</h3>
     {% endif %}

		<h3>Total Calories consumed: {{ total_calories}}</h3>

    </div>
    </div>
    </div>


{% endblock %}

project_kkal/calorie_calculator/ingredients/templates/ingredients/register.html
{% extends 'ingredients/base.html' %}

{% block title %} Ingredients|Registration{% endblock %}
{% block body %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Register</button>
  </form>
{% endblock %}